name: Deployment
run-name: ${{ github.actor }} is 🚀 deploy website on push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy_ftp:
    environment: SECRET
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🔧 Install dependencies and build
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: 🔧 Install dependencies
        run: |
          npm install

      - name: 🔧 Build
        run: |
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-DEPLOY-Action@v4.3.4
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          local-dir: dist/
          server-dir: www/
          dangerous-clean-slate: false